/**
 * ExpectedPages — renders the site-map route table from the single typed
 * source in `lib/site-map.ts` (#58). Status badges are derived from
 * `Route.status`; no hand-maintained duplicates.
 *
 * The markdown equivalent (`docs/SITE_MAP.md`) is generated by
 * `scripts/generate-site-map-md.ts` and verified in CI.
 */

import { ROUTES, type RouteStatus } from "@/lib/site-map";

const STATUS_LABEL: Record<RouteStatus, string> = {
  live:     "Live",
  scaffold: "Scaffold",
  planned:  "Planned",
};

const STATUS_STYLE: Record<RouteStatus, React.CSSProperties> = {
  live:     { color: "var(--accent-2)", fontWeight: 600 },
  scaffold: { color: "var(--accent)",   fontWeight: 600 },
  planned:  { color: "var(--text-muted)" },
};

export function ExpectedPages() {
  return (
    <section className="section site-map" id="site-map">
      <span className="tag">Site map</span>
      <h2>Expected pages (delivery backlog)</h2>
      <p style={{ color: "var(--text-muted)", maxWidth: 720 }}>
        This table is generated from{" "}
        <code>lib/site-map.ts</code> — the single source of truth between
        product and engineering. Update the source and run{" "}
        <code>npm run gen:site-map</code> to keep{" "}
        <code>docs/SITE_MAP.md</code> in sync.
      </p>
      <div style={{ overflowX: "auto", marginTop: 16 }}>
        <table>
          <thead>
            <tr>
              <th>Route</th>
              <th>Purpose</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {ROUTES.map((route) => (
              <tr key={route.path}>
                <td><code>{route.path}</code></td>
                <td>{route.purpose}</td>
                <td style={STATUS_STYLE[route.status]}>
                  {STATUS_LABEL[route.status]}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}
