/**
 * Site map — single typed source of route data (#58).
 *
 * This module is the sole owner of:
 *   - the route table rendered by `components/expected-pages.tsx`
 *   - the nav links used by `components/site-nav.tsx`
 *   - `docs/SITE_MAP.md` (generated by `scripts/generate-site-map-md.ts`)
 *
 * To add or change a route:
 *   1. Edit the `ROUTES` array below.
 *   2. Run `npm run gen:site-map` to regenerate `docs/SITE_MAP.md`.
 *   3. Commit both files — CI will fail if they diverge.
 */

export type RouteStatus = "live" | "scaffold" | "planned";

export interface Route {
  /** URL path, e.g. "/product" */
  path: string;
  /** Human-readable purpose shown in the site-map table */
  purpose: string;
  /** Current delivery status */
  status: RouteStatus;
  /** Whether to show this route in the top-level navigation */
  showInNav?: boolean;
  /** Short label used in the nav (defaults to the last path segment, capitalised) */
  navLabel?: string;
}

export const ROUTES: Route[] = [
  {
    path: "/",
    purpose: "Marketing hub + site map",
    status: "scaffold",
    showInNav: false,
  },
  {
    path: "/product",
    purpose: "Personas, pricing hooks, integration story",
    status: "scaffold",
    showInNav: true,
    navLabel: "Product",
  },
  {
    path: "/contracts",
    purpose: "Soroban modules and interaction flows",
    status: "scaffold",
    showInNav: true,
    navLabel: "Contracts",
  },
  {
    path: "/operators",
    purpose: "Dashboard preview for AI gateways",
    status: "scaffold",
    showInNav: true,
    navLabel: "Operators",
  },
  {
    path: "/compliance",
    purpose: "Audit exports and policy packs",
    status: "scaffold",
    showInNav: true,
    navLabel: "Compliance",
  },
  {
    path: "/roadmap",
    purpose: "Milestones vs grants",
    status: "scaffold",
    showInNav: true,
    navLabel: "Roadmap",
  },
  {
    path: "/contributors",
    purpose: "Good first issues and guild roles",
    status: "scaffold",
    showInNav: true,
    navLabel: "Contributors",
  },
  {
    path: "/docs",
    purpose: "Technical reference hub",
    status: "scaffold",
    showInNav: true,
    navLabel: "Docs",
  },
];

/** Nav links derived from the route table — the only source used by SiteNav. */
export const NAV_LINKS: { label: string; href: string }[] = ROUTES.filter(
  (r) => r.showInNav,
).map((r) => ({
  label: r.navLabel ?? r.path.slice(1).replace(/^./, (c) => c.toUpperCase()),
  href: r.path,
}));
