/**
 * generate-site-map-md.ts
 *
 * Generates `docs/SITE_MAP.md` from `lib/site-map.ts` (#58).
 * Run via: npm run gen:site-map
 *
 * CI runs this and fails if the committed file differs from the output,
 * preventing the table from drifting out of sync with the route list.
 */

import { writeFileSync } from "fs";
import { join } from "path";
import { ROUTES } from "../lib/site-map";

const STATUS_LABEL: Record<string, string> = {
  live:     "✅ Live",
  scaffold: "🏗 Scaffold",
  planned:  "📋 Planned",
};

const rows = ROUTES.map(
  (r) =>
    `| \`${r.path}\` | ${r.purpose} | ${STATUS_LABEL[r.status] ?? r.status} |`,
).join("\n");

const md = `# Site Map
<!-- AUTO-GENERATED by scripts/generate-site-map-md.ts — do not edit by hand.
     Run \`npm run gen:site-map\` to regenerate after editing lib/site-map.ts. -->

| Route | Purpose | Status |
|-------|---------|--------|
${rows}
`;

const outPath = join(import.meta.dirname, "..", "docs", "SITE_MAP.md");
writeFileSync(outPath, md, "utf8");
console.log("✓ docs/SITE_MAP.md written");
